# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095e3fd1808fba03af2aef8580da6cf633c931603b5c71a4458bfbbe63638c4715aa170bc2f16124e538b98a92c3d331b82a95efacbd734c784f768416ef1686

test:
  secret_key_base: e707c53ef9ac1aed633cbff37be17003674eaf8149761bb0029d58d174dfed66f3ca9e23f8ec5c4125263e778238d73bc8a5df8f1724e9c78ed660d7f09c33b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
